---
"/parameters":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/parameters"
    parameters: []
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/parameters/{component}":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/parameters/:component"
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/parameters/{component}/{vhost}":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/parameters/:component/:vhost"
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/parameters/{component}/{vhost}/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/parameters/:component/:vhost/:name"
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME
    summary: "/parameters/:component/:vhost/:name"
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME
    summary: "/parameters/:component/:vhost/:name"
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/global-parameters":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/global-parameters"
    parameters: []
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/global-parameters/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/global-parameters/:name"
    parameters:
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME
    summary: "/global-parameters/:name"
    parameters:
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME
    summary: "/global-parameters/:name"
    parameters:
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/policies":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/policies"
    parameters: []
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/policies/{vhost}":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/policies/:vhost"
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/policies/{vhost}/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME
    summary: "/policies/:vhost/:name"
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME
    summary: "/policies/:vhost/:name"
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME
    summary: "/policies/:vhost/:name"
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME
    operationId: CHANGEME
    responses:
      '200':
        description: CHANGEME
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
