---
parameters:
  type: array
  items:
    "$ref": "#/parameter"
global-parameters:
  type: array
  items:
    "$ref": "#/parameter"
parameter:
  type: object
  properties:
    name:
      type: string
    value:
      type: string
    component:
      type: string
      description: TODO
    vhost:
      type: string
global-parameter:
  type: object
  properties:
    name:
      type: string
    value:
      type: string
    component:
      nullable: true
      type: string
    vhost:
      nullable: true
      type: string
PutParameterRequestBody:
  type: object
  properties:
    value:
      type: string
  required:
  - value
