---
parameters:
  type: object
  properties:
    CHANGEME:
      type: string
      description: CHANGEME
policies:
  type: array
  items:
    "$ref": "#/policy"
policy:
  type: object
  properties:
    CHANGEME:
      type: string
      description: CHANGEME
