name: Benchmark
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  benchmark-master:
    name: Build & Benchmark master

    runs-on: ubuntu-20.04
    steps:
      - name: Install Crystal
        run: sudo snap install crystal --classic

      - name: Install dependencies
        run: sudo apt-get install -y libsystemd-dev dpkg fakeroot help2man lintian build-essential gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Build
        run: |
          shards install --production
          shards build --production --release
      
      - name: Benchmark
        run: |
          ./bin/avalanchemq -D data &
          ./bin/avalanchemqperf throughput -j -q -z 60

  benchmark:
    name: Build & Benchmark
    runs-on: ubuntu-20.04
    steps:
      - name: Install Crystal
        run: sudo snap install crystal --classic

      - name: Install dependencies
        run: sudo apt-get install -y libsystemd-dev dpkg fakeroot help2man lintian build-essential gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          shards install --production
          shards build --production --release
      
      - name: Benchmark
        run: |
          ./bin/avalanchemq -D data &
          ./bin/avalanchemqperf throughput -j -q -z 60
