name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shards install
        run: shards install

      - name: Spec
        run: crystal spec --no-color --order random

  java-client-test:
    name: RabbitMQ java client test
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libsystemd-dev openjdk-11-jre-headless gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev python-is-python3 python3

      - name: Install Crystal
        run: sudo snap install crystal --classic

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build avalanchemq
        run: |
          crystal --version
          shards --version
          shards install --production
          shards build --production avalanchemq

      - name: Run avalanchemq in background
        run: bin/avalanchemq --data-dir /tmp/amqp &

      - name: Clone java client
        run: git clone --depth 1 https://github.com/84codes/rabbitmq-java-client.git

      - name: Run java tests
        run: |
          cd rabbitmq-java-client
          make deps
          ./mvnw verify -P '!setup-test-cluster' -Dit.test=FunctionalTests

  bunny-test:
    name: Bunny client test
    runs-on: ubuntu-20.04

    steps:
      - name: Setup bundler cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-test${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-test

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Installing bundler
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.token }}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build avalanchemq
        run: |
          crystal --version
          shards --version
          shards install --production
          shards build --production avalanchemq

      - name: Run avalanchemq in background
        run: bin/avalanchemq --data-dir /tmp/amqp &

      - name: Clone Bunny
        run: git clone --depth 1 git@github.com:ruby-amqp/bunny.git

      - name: Run specs
        run: cd bunny
          CI=true bundle exec rspec --pattern "spec/*/integration/*_spec.rb, spec/issues/*_spec.rb" --exclude-pattern "**/*/tx_*, **/*/tls_*, **/*/connection_recovery_*"
