name: CI
on: [push]

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: MeilCli/setup-crystal-action@v3.0.0
        with:
          crystal_version: 0.35.0
          shards_version: 0.11.1
      - name: Install libsystemd-dev
        run: sudo apt-get install -y libsystemd-dev
      - name: Shards install
        run: shards install
      - name: Spec
        run: crystal spec --no-color
      - name: Lint
        run: bin/ameba
