name: Deb
on: [push]

jobs:
  build_deb:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Crystal
        uses: MeilCli/setup-crystal-action@v3.0.0
        with:
          crystal_version: 0.35.1
          shards_version: 0.11.1

      - name: Install dependencies
        run: sudo apt-get install -y libsystemd-dev dpkg fakeroot help2man lintian

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Ubuntu release name
        run: |
          echo "::set-env name=CODENAME::$(lsb_release -cs)"

      - name: Get git tag
        run: |
          echo "::set-env name=TAG::$(git describe)"

      - name: Build deb package
        run: build/deb 1

      - name: Upload deb package
        uses: actions/upload-artifact@v2
        with:
          path: builds/**/*.deb
          name: avalanchemq-${{ env.TAG }}-1-${{ env.CODENAME }}.deb
